### ISSUE TITLE
fastfurnace lost items

### ISSUE THREAD

**Issue by HeberonYT** [Shadows-of-Fire/FastFurnace#11]
I do not know if it's the right place, but spongeforge does not usually help with compatibility issues with mods.
I'm using the SkyFactory4 modpack (v4.0.2) on a spongeForge RC3616 server and everything worked fine.
But I updated sponge to RC3679 because it repairs serious bugs and now the FastFurnace ovens do not work. Sometimes what is cooked is lost, other times the oven stays on all the time even when it is empty.
I do not attach a log because there are no errors or warning messages.

**Comment by Shadows-of-Fire** [comment]
I mean, if it worked before, and sponge changed, then it very much sounds like a bug with sponge.  Don't think theres anything I can do about it.

**Comment by ktole1999** [comment]
Sponge says this bug is you and not them. Can you confirm if this has been resolved in latest version. This issue is happening in Skyfactory 4.0.3 pack but i cant just update mod. 

https://github.com/SpongePowered/SpongeForge/issues/2702
