### ISSUE TITLE
Server crash when i try to install fast furnace or fast workbench

### ISSUE THREAD

**Issue by TheYoloPanda** [Shadows-of-Fire/FastFurnace#17]
`---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 13/09/19 20.19
Description: Exception in server tick loop

net.minecraftforge.fml.LoadingFailedException: null
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:165) ~[?:?] {}
	at net.minecraftforge.fml.server.ServerModLoader.begin(ServerModLoader.java:45) ~[?:?] {}
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:121) ~[?:?] {pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:598) [?:?] {pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_221] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.14.4
	Minecraft Version ID: 1.14.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_221, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 946091168 bytes (902 MB) / 1628438528 bytes (1553 MB) up to 2796552192 bytes (2667 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xms1024M -Xmx3000M
	ModLauncher: 3.2.0+60+b86c1d4
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/eventbus-1.0.0-service.jar eventbus PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-1.0.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar runtimedistcleaner PLUGINSERVICE 
		/forge-1.14.4-28.1.0.jar fml TRANSFORMATIONSERVICE 
	FML: 28.1
	Forge: net.minecraftforge:28.1.0
	FML Language Providers: 
		javafml@28.1
		minecraft@1
	Mod List: 
		FastFurnace-1.14.4-2.2.0.jar FastFurnace {fastfurnace@2.2.0 NONE}
		FastWorkbench-1.14.4-2.1.0.jar FastWorkbench {fastbench@2.1.0 NONE}
		FTBUtilitiesBackups-2.0.0.10.jar FTB Utilities: Backups {ftbbackups@2.0.0.10 NONE}
		jei-1.14.4-6.0.0.11.jar Just Enough Items {jei@6.0.0.11 NONE}
		Morpheus-1.14.4-4.2.42.jar Morpheus {morpheus@version NONE}
		ServerTabInfo-1.14.4-1.2.5-b2.jar Server Tab Info {servertabinfo@1.2.5-b2 NONE}
		forge-1.14.4-28.1.0-universal.jar Forge {forge@28.1.0 NONE}
		forge-1.14.4-28.1.0-server.jar Minecraft {minecraft@1.14.4 NONE}
	Data Packs: 
	Is Modded: Definitely; Server brand changed to 'forge'
	Type: Dedicated Server (map_server.txt)`

**Comment by Shadows-of-Fire** [comment]
You need to provide the full debug.log file in order for this error to be diagnosed.  Its possible I just need to update to the forge RB, which I have not done yet, but it may be something else.
