### ISSUE TITLE
villager cannot claim blast furnace and smoker as a job site block

### ISSUE THREAD

**Issue by G107040504** [Shadows-of-Fire/FastFurnace#19]
Hello, i use FastFurnace in my server and i found that villager cannot claim both blast furnace and smoker as their job site block. So, the villager cannot change their profession into Armorer and Butcher. It does not happen without FastFurnace.
Forge: forge-1.14.4-28.0.102
FastFurnace: FastFurnace-1.14.4-2.2.0

**Comment by Shadows-of-Fire** [comment]
Ah, yeah, probably the same issue from apoth and the fletching table.

**Comment by G107040504** [comment]
After update to 2.2.3, it still not work.

Forge: 1.14.4-28.1.20
FastFurnace: 1.14.4-2.2.3
Placebo: 1.14.4-2.2.1
