### ISSUE TITLE
Furnace stops cooking after 1 item is cooked 

### ISSUE THREAD

**Issue by CertainlyNotLuke** [Shadows-of-Fire/FastFurnace#22]
Hey there. I am a Staff Manager on a server of a streamer, and we implemented this mod into our server due to it sounding promising and helpful. We are experiencing an issue though, with furnaces not cooking more after 1 of the items is cooked (ex. Iron Ore) having to manually take out the ingots each time is a hassle. Any fix for this?

**Comment by Shadows-of-Fire** [comment]
No, this is a bug in customnpcs
