### ISSUE TITLE
[1.15.2] Question: Modded Furnaces

### ISSUE THREAD

**Issue by TheUntamed** [Shadows-of-Fire/FastFurnace#24]
Does this mod affect Furnaces added by mods? Like Brick Furnace or Iron Furnace?

**Comment by cech12** [comment]
This mod only affect the vanilla furnaces. But my Brick Furnace mod adds also the mechanics of this mod.

**Comment by TheUntamed** [comment]
Can you add some sort of api that allows other modders to use your FastFurnace method for their furnaces?

**Comment by cech12** [comment]
Sorry, but I am only the developer of the Brick Furnace mod ^^
I searched the code of this mod to use some parts to make my furnaces work more efficient. Maybe you can do the same? :)

**Comment by TheUntamed** [comment]
I'm not a mod dev. I'm a modpack dev. I thought about adding your mod (Brick Furnace) and other Furnace mods (like Iron Furnace) and were curios about performance.

**Comment by cech12** [comment]
Ah ok :) Maybe you can ask the mod developers of the other furnace mods if they are using the performance enhancements :)

**Comment by TheUntamed** [comment]
I will

**Comment by Shadows-of-Fire** [comment]
There is nothing to be done for modded furnaces.  They are responsible for not copying vanilla's bad practices.
