### ISSUE TITLE
Furnace Smelts only one item.

### ISSUE THREAD

**Issue by SMHerobrine** [Shadows-of-Fire/FastFurnace#26]
If there is an item in the output slot the furnace stops cooking food, ores, or anything like that.

Only works if FF is installed alone. 
It's a conflict with CustomNPCs

The issue is in The SM Modpack + and other modpacks that have fast furnace and CustomNPCs installed

[You can Download the SM Modpack to see it](https://www.curseforge.com/minecraft/modpacks/the-sm-modpack)

**Comment by Shadows-of-Fire** [comment]
it's a bug in custom npc's

**Comment by SMHerobrine** [comment]
But how can it be fixed?

**Comment by EverNife** [comment]
I am interested in fixing this issue.

Just tell me how you found out it was CustomNPCs and i will try to fix it.

**Comment by SMHerobrine** [comment]
Ask Shadows-of-Fire he said it was bug with CustomNPCs
