### ISSUE TITLE
[1.16.1] Furnace / Blast Furnace provides light when placing it down without anything cooking.

### ISSUE THREAD

**Issue by Gbergz** [Shadows-of-Fire/FastFurnace#27]
Title^,
Furnace or the Blast Furnace provides light when placing them without anything cooking in them.

### Versions:

**Minecraft:** 1.16.1
**Forge:** 32.0.69
**FastFurnace Version:** 4.0.0

GIF with FastFurnace: https://gyazo.com/4a6949c2a5c856ef130590ce3747534e

GIF without FastFurnace: https://gyazo.com/ba3a9c781f2dc88fe5f2f9c96b694473

Edit: Tried this in a clean instance w/ Only FastFurnace & Placebo installed and it still happens.

**Comment by NielsPilgaard** [comment]
I can confirm that this is fixed in `FastFurnace-1.16.1-4.1.1`, thanks.
