### ISSUE TITLE
When I remove the mod the furnace textures get removed

### ISSUE THREAD

**Issue by Dasvin96** [Shadows-of-Fire/FastFurnace#28]
Once I remove the mod, the furnace textures go to black and pink, any ideas why this happened?

**Comment by Shadows-of-Fire** [comment]
Just what happens, break and replace them

**Comment by STiiTCHDev** [comment]
Unfortunatly, break and replace doesn't solve the problem on my server, any other known solution ? Installing texture pack not solve more.
