### ISSUE TITLE
Some furnaces lag or desync (other mods involved)

### ISSUE THREAD

**Issue by KironaDragryph** [Shadows-of-Fire/FastFurnace#29]
I'm playing the Skyblock 4 modpack, and with FastFurnace enabled, my slab furnaces (from the Slab Machines mod) don't operate at the same speed. One seems to work normally, but the second one seems to hang/pause randomly, but quite often, resulting in it actually processing input at roughly half speed.

Disabling only FastFurnace fixes the issue. I haven't been able to test it with a normal furnace yet but figured I should let you know. I'm guessing it's an issue with this mod and not Slab Machines because, when this mod is disabled, they perform as expected.

**Comment by Shadows-of-Fire** [comment]
Why would it be an issue with this mod?  This mod has no mod integration of any sort, nor any code that modifies either vanilla or mod code.
