### ISSUE TITLE
Feature Request: Support ModUpdater

### ISSUE THREAD

**Issue by dhouck** [Shadows-of-Fire/FastFurnace#30]
[ModUpdater](https://gitea.thebrokenrail.com/TheBrokenRail/ModUpdater) is a Fabric mod to help keep other Fabric mods up-to-date.  It should be relatively simple to [get it working](https://gitea.thebrokenrail.com/TheBrokenRail/ModUpdater/src/branch/master/MOD_DEVELOPER.md) for FastFurnace by adding a handful of lines to the `fabric.mod.json` file, although I canʼt actually find where that file comes from in this repository.

**Comment by Shadows-of-Fire** [comment]
This is not a fabric mod

**Comment by dhouck** [comment]
Thank you for the quick reply even when the issue was nonsense.  I got confused because somebody ported it to Fabric at https://www.curseforge.com/minecraft/mc-mods/fast-furnace-for-fabric; Iʼll open an issue with them instead.
