### ISSUE TITLE
Blast Furnace and Smoker aren't recognized by villagers as job blocks

### ISSUE THREAD

**Issue by Chewypuppielover** [Shadows-of-Fire/FastFurnace#32]
I have left a villager next to both a Blast Furnace and Smoker for several in game days and it never once claimed a job.
A thought: 
I installed JEI Professions and it says that those jobs' blocks are the FastFurnace versions, at least the tag says it is, but only the Minecraft versions are acquirable. (Looking at it again, I don't think this is the reason)
![2021-02-16_22 46 37](https://user-images.githubusercontent.com/35238835/108162039-864e6280-70a9-11eb-8661-7003fc974fbd.png)

![2021-02-16_22 46 34](https://user-images.githubusercontent.com/35238835/108161772-fc9e9500-70a8-11eb-9b64-765c51848dce.png)

**Comment by Shadows-of-Fire** [comment]
Don't think this was ever on my end to begin with. Impossible as of 4.5.0 since RR is no more.
