### ISSUE TITLE
add ci and tags for releases

### ISSUE THREAD

**Issue by danielphan2003** [Shadows-of-Fire/FastFurnace#38]

**Comment by Shadows-of-Fire** [comment]
what

**Comment by danielphan2003** [comment]
> what 

I meant to do so as I can just grab your jar file directly on GitHub releases tab on your repo without going through CurseForge.

You don't have to build the jar file and upload it to GitHub yet again, as there are automation tasks that you can use in GitHub Actions, so that everytime you tag a release it would just build the files for you.

I might be able to whip up a PR for this, but for now I want to hear your opinion on this.

**Comment by Shadows-of-Fire** [comment]
I don't want to deal with maintaining a CI pipeline on github for this (or any) of the projects.  CF is the only supported distribution center.
