### ISSUE TITLE
1.18.1 not saving items inside furnace

### ISSUE THREAD

**Issue by SCDevel** [Shadows-of-Fire/FastFurnace#40]
I tested all the furnaces and after saving and exiting a world and joining again all the items inside the furnace disappear.
I tested with 6.0.0 & 6.0.1

**Comment by Shadows-of-Fire** [comment]
The mixins that FF applies do not edit the furnace inventory or the saving functions, nor can I reproduce this in dev or an isolated environment.  I suspect you have another mod causing this problem.
