### ISSUE TITLE
Furnace texture missing after installing mod. 

### ISSUE THREAD

**Issue by Erosion139** [Shadows-of-Fire/FastFurnace#41]
The black and pink texture is on every furnace despite replacing the furnaces or placing new ones from the creative inventory or crafting them in survival. The furnaces function properly but the textures are missing. 

Mod version: 1.12.2-1.3.1
Forge: 14.23.5.2855

Let me know if you need any log files or mod lists

**Comment by Shadows-of-Fire** [comment]
1.12 has been out of support for over a year now

**Comment by MagmaSlime123** [comment]
Remove the old versions.
