### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Th3Br0k3nmama** [Shadows-of-Fire/FastFurnace#42]
i have fast furnace, the correct one for my version, but it is not working. its in my mods folder its just not working on my server world i need help as soon as you can please

**Comment by Shadows-of-Fire** [comment]
define not working

**Comment by Th3Br0k3nmama** [comment]
oh sorry i have been busy but i mean i have the 1.18..2 version of fast furnace in my servers mods folder as shown but it is not working on my server actively. it does not cook things well, fast. i have used it before in the past on a 1.12 server and know that it can work i just am uncertain why the version 1.18.2 which is my server version now and the version i downloaded for my server, is not working on my server as you can see that it is indeed the right version and is there in my mods folder
![fast furnace 1](https://user-images.githubusercontent.com/102869263/169728971-d53a22ec-a263-4ee1-9ee2-01c760909517.PNG)

**Comment by Shadows-of-Fire** [comment]
FF does not increase burn speed, it is a performance mod

**Comment by Th3Br0k3nmama** [comment]
what do you mean by performance than?

**Comment by cech12** [comment]
Please read the mod description: https://www.curseforge.com/minecraft/mc-mods/fastfurnace
