### ISSUE TITLE
Crash with FastFurnace 1.2.1

### ISSUE THREAD

**Issue by CactusDuud** [Shadows-of-Fire/FastFurnace#5]
[crashlog](https://paste.dimdev.org/emuqumuqis.mccrash)

FastWorkbench (1.6.0) also seems to cause problems. The crash log gives little information (to me at least), but the game worked fine after I removed these too, so I'm fairly certain it's for one of these.

EDIT: Running Forge 1.12.2 14.23.5.2776

**Comment by Shadows-of-Fire** [comment]
This isn't being caused by either of my mods.  I think something is probably reacting badly to registry replacements, but I don't know what.
