### ISSUE TITLE
Only allows one item in output slot (Conflict)

### ISSUE THREAD

**Issue by corgiblu** [Shadows-of-Fire/FastFurnace#6]
As the title states it will only let one item go into the output slot. If I put 5 logs in the top and fuel in the bottom, it will only make 1 charcoal and then stop. I have to take that 1 charcoal out before it starts making another one. It's not an issue with stacksize because it stacks fine in my inventory. I have tested it and works properly with only FastFurnace installed.

Mod list: https://paste.dimdev.org/itedarucej.md

FastFurnace Version: 1.12.2 1.2.1
Forge Version: 14.23.5.2772

**Comment by corgiblu** [comment]
Experimented and it happens with FastFurnace and CustomNPCs installed.
Log: https://paste.dimdev.org/uvovokuceh.md

(versions of other 2 are still the same) CustomNPC Version: (26Aug18)

**Comment by Shadows-of-Fire** [comment]
This is likely on their end, and since CNPC is closed source, it's not something that I can fix or even look into.

**Comment by Brycey92** [comment]
Someone asked Noppes and he said he couldn't fix it on his side.

![image](https://user-images.githubusercontent.com/666399/55210837-b80d6600-51bf-11e9-83fc-e7e1bbf6181a.png)

**Comment by Brycey92** [comment]
There's a reddit thread [here](https://www.reddit.com/r/feedthebeast/comments/a6iz8v/furnace_doesnt_want_more_than_1_item_in_output/) that looks like they may have found the source of the issue.

**Comment by Shadows-of-Fire** [comment]
That makes the issue entirely on their end.  That significantly breaks many comparison methods.  Nobody should be randomly attatching NBT information to every itemstack.

**Comment by Brycey92** [comment]
Shadows added a config option `Strict Matching` in 79a25e36d31deeec090971dc4fb548e378ad78d4/v1.3.1 which you can set to `false` as a workaround for this issue.
