### ISSUE TITLE
Texture furnace / workbench

### ISSUE THREAD

**Issue by Heriptik** [Shadows-of-Fire/FastFurnace#7]
Hello, i use a texture pack in my server and the texture Furnace / workbench does not appear

Exemple screen : 

No texture pack : [https://image.noelshack.com/fichiers/2019/05/6/1549113550-2019-02-02-14-18-25.png](https://image.noelshack.com/fichiers/2019/05/6/1549113550-2019-02-02-14-18-25.png)

Texture pack : [https://image.noelshack.com/fichiers/2019/05/6/1549113786-2019-02-02-14-23-00.png](https://image.noelshack.com/fichiers/2019/05/6/1549113786-2019-02-02-14-23-00.png)

Same FastWorkbench

thanks

**Comment by Shadows-of-Fire** [comment]
Are you using LiteLoader?

**Comment by Heriptik** [comment]
Yes same problem

**Comment by Shadows-of-Fire** [comment]
Yeah the bug is caused by liteloader, and liteloader appears to be out of active development.

**Comment by Heriptik** [comment]
Even without the problem appears
