### ISSUE TITLE
Blood Arsenal incompatibility

### ISSUE THREAD

**Issue by Pulz-TCP** [Shadows-of-Fire/FastFurnace#9]
https://paste.dimdev.org/xezubejiva.mccrash

Forge: 2784
Blood Arsenal: 2.2.0.27
Blood Magic: 2.4.0.102
FastFurnace: 1.2.3

I have 100% confirmed that the above crash is only present when FastFurnace is added alongside any 1.12 version of Blood Arsenal.

**Comment by Shadows-of-Fire** [comment]
Possibly a result of BA incorrectly handling replacements?  Nothing I can do about it from my end.
